name: Announcer
main: net.TheDgtl.Announcer.Announcer
version: 1.0.1
author: Drakia
website: http://www.thedgtl.net
commands:
  announcer:
    description: Reload the announcement file
    usage: /<command> reload - Reload the announcement file